"""Add contact fields to events

Revision ID: 0b492d2518be
Revises: 21a810653d1a
Create Date: 2025-12-25 08:05:34.358803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b492d2518be'
down_revision = '21a810653d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_manager_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_manager_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('safety_manager_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('safety_manager_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('business_manager_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_manager_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('board_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('board_email')
        batch_op.drop_column('business_manager_phone')
        batch_op.drop_column('business_manager_email')
        batch_op.drop_column('safety_manager_phone')
        batch_op.drop_column('safety_manager_email')
        batch_op.drop_column('event_manager_phone')
        batch_op.drop_column('event_manager_email')

    # ### end Alembic commands ###
