"""Add EventRegistration model for user event registrations

Revision ID: 21a64fcc45d4
Revises: a242add47f46
Create Date: 2026-01-10 20:22:28.386423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a64fcc45d4'
down_revision = 'a242add47f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('has_ticket', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('opted_early_arrival', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('opted_late_departure', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('opted_vehicle_access', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='unique_user_event_registration')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    # ### end Alembic commands ###
