"""Add email/password authentication

Revision ID: 320731d9d95b
Revises: e1bad3965dcb
Create Date: 2025-12-24 20:17:42.115635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320731d9d95b'
down_revision = 'e1bad3965dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email_verification_token'])
        batch_op.create_unique_constraint(None, ['password_reset_token'])

    # Data migration: Set email_verified=True for existing OAuth users
    # All existing users have OAuth authentication, so they should be considered verified
    op.execute("UPDATE users SET email_verified = true WHERE id IN (SELECT DISTINCT user_id FROM oauth_providers)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_reset_sent_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
