"""Add backup lead support to clusters and teams

Revision ID: 4a8896790836
Revises: b35d73e00638
Create Date: 2025-12-29 20:36:42.325506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8896790836'
down_revision = 'b35d73e00638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_cluster_lead_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enable_cluster_lead', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('enable_backup_cluster_lead', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_foreign_key(None, 'users', ['backup_cluster_lead_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_team_lead_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enable_team_lead', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('enable_backup_team_lead', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_foreign_key(None, 'users', ['backup_team_lead_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enable_backup_team_lead')
        batch_op.drop_column('enable_team_lead')
        batch_op.drop_column('backup_team_lead_id')

    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enable_backup_cluster_lead')
        batch_op.drop_column('enable_cluster_lead')
        batch_op.drop_column('backup_cluster_lead_id')

    # ### end Alembic commands ###
