"""Add custom amenities field to camps

Revision ID: 721e7cddfc80
Revises: b06bda10cecf
Create Date: 2025-12-27 08:51:12.618002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721e7cddfc80'
down_revision = 'b06bda10cecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_amenities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.drop_column('custom_amenities')

    # ### end Alembic commands ###
