"""Move location from camps to camp_event_associations

Revision ID: 7ccf94da4b79
Revises: 721e7cddfc80
Create Date: 2025-12-27 09:00:18.492224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccf94da4b79'
down_revision = '721e7cddfc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_event_associations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('camp_event_associations', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
