"""Add role-based access control

Revision ID: 9d3585a42e7d
Revises: 320731d9d95b
Create Date: 2025-12-25 06:36:54.178169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3585a42e7d'
down_revision = '320731d9d95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='member', nullable=False))

    # ### end Alembic commands ###

    # Data migration: Set initial roles for existing users
    # Set user id=1 as global admin
    op.execute("UPDATE users SET role = 'global admin' WHERE id = 1")

    # Set all other users as members (redundant but explicit)
    op.execute("UPDATE users SET role = 'member' WHERE id != 1")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
