"""Add event options fields

Revision ID: a242add47f46
Revises: b5d5e1e746ae
Create Date: 2025-12-31 08:23:30.534358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a242add47f46'
down_revision = 'b5d5e1e746ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_early_arrival', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('early_arrival_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_late_departure', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('late_departure_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_accessibility_assistance', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('has_drinking_water', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('has_ice_available', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('has_vehicle_access', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('custom_event_options', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('custom_event_options')
        batch_op.drop_column('has_vehicle_access')
        batch_op.drop_column('has_ice_available')
        batch_op.drop_column('has_drinking_water')
        batch_op.drop_column('has_accessibility_assistance')
        batch_op.drop_column('late_departure_days')
        batch_op.drop_column('has_late_departure')
        batch_op.drop_column('early_arrival_days')
        batch_op.drop_column('has_early_arrival')

    # ### end Alembic commands ###
