"""Add camp management and camp-event associations

Revision ID: a59bcf18a042
Revises: 1ab380403379
Create Date: 2025-12-26 18:36:41.744819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59bcf18a042'
down_revision = '1ab380403379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('max_sites', sa.Integer(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('has_communal_kitchen', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_communal_space', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_art_exhibits', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_member_activities', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_non_member_activities', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camp_event_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'event_id', name='uix_camp_event')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camp_event_associations')
    op.drop_table('camps')
    # ### end Alembic commands ###
