"""Add camp membership system

Revision ID: b06bda10cecf
Revises: c14501432a54
Create Date: 2025-12-26 21:00:33.037910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06bda10cecf'
down_revision = 'c14501432a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camp_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'user_id', name='uix_camp_user')
    )
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_approval_mode', sa.String(length=20), server_default='manager_only', nullable=False))

    # Data migration: Auto-add camp creators as managers
    connection = op.get_bind()
    camps = connection.execute(sa.text("SELECT id, creator_id, created_at FROM camps"))

    for camp in camps:
        connection.execute(
            sa.text("""
                INSERT INTO camp_members (camp_id, user_id, status, role, requested_at, approved_at)
                VALUES (:camp_id, :user_id, 'approved', 'manager', :created_at, :created_at)
            """),
            {
                'camp_id': camp.id,
                'user_id': camp.creator_id,
                'created_at': camp.created_at
            }
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.drop_column('member_approval_mode')

    op.drop_table('camp_members')
    # ### end Alembic commands ###
