"""Add volunteer organizational structure: Clusters, Teams, TeamMembers, and camp leadership roles

Revision ID: b35d73e00638
Revises: 7c8a0fea8f05
Create Date: 2025-12-28 22:41:56.532778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35d73e00638'
down_revision = '7c8a0fea8f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster_lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'name', name='uq_cluster_camp_name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'name', name='uq_team_cluster_name')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camp_lead_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('backup_camp_lead_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enable_camp_lead', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('enable_backup_camp_lead', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_foreign_key(None, 'users', ['camp_lead_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['backup_camp_lead_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enable_backup_camp_lead')
        batch_op.drop_column('enable_camp_lead')
        batch_op.drop_column('backup_camp_lead_id')
        batch_op.drop_column('camp_lead_id')

    op.drop_table('team_members')
    op.drop_table('teams')
    op.drop_table('clusters')
    # ### end Alembic commands ###
