"""Add user profile fields and inventory items

Revision ID: c14501432a54
Revises: a59bcf18a042
Create Date: 2025-12-26 20:21:17.419532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14501432a54'
down_revision = 'a59bcf18a042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_shared_gear', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('home_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mobile_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('work_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), server_default='US', nullable=False))
        batch_op.add_column(sa.Column('email_change_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_change_new_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_change_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email_change_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_change_sent_at')
        batch_op.drop_column('email_change_new_email')
        batch_op.drop_column('email_change_token')
        batch_op.drop_column('country')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line2')
        batch_op.drop_column('address_line1')
        batch_op.drop_column('work_phone')
        batch_op.drop_column('mobile_phone')
        batch_op.drop_column('home_phone')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('preferred_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('inventory_items')
    # ### end Alembic commands ###
